name: The Feather Jade
favicon: null
layout_spectrum: 1
typography_spectrum: 0.35739493533037603
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3f1f2'
    - '#cfbfbf'
    - '#25323b'
    - '#c73e57'
    - '#6b6c6e'
  brandStrength: 0
  lightness: 0.1875
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
